server {
    listen 80;
    server_name _;

    allow 10.10.8.0/21;
    allow 10.45.0.0/21;
    deny all;

    client_max_body_size 2m;
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
